// SALIN DAN GANTI SELURUH ISI SCRIPT.JS DENGAN INI

import { dataPromise } from './data-loader.js';

document.addEventListener('DOMContentLoaded', async () => {
    console.log("Menunggu data dari data-loader...");
    try {
        const { productsDB, musimAktif } = await dataPromise;
        console.log("Data siap, menjalankan aplikasi utama.");
        main(productsDB, musimAktif);
    } catch (error) {
        document.body.innerHTML = `<h1>Gagal Memuat Aplikasi</h1><p>Penyebab: ${error.message}. Pastikan koneksi internet dan konfigurasi Firebase Anda benar.</p>`;
    }
});

function main(productsDB, musimAktif) {
    const seasonalSlogans = { sekolah: "Produk Musiman: Kembali ke Sekolah!", lebaran: "Spesial Lebaran Penuh Berkah", remaja: "Gaya Trendy Kekinian untuk Kamu" };
    let notificationTimeout;
    function showCustomNotification(message) { const notification = document.getElementById('cart-notification'); if (!notification) return; clearTimeout(notificationTimeout); notification.textContent = message; notification.classList.add('show'); notificationTimeout = setTimeout(() => { notification.classList.remove('show'); }, 2500); }
    function getCart() { const cart = localStorage.getItem('tokoMinimalisCart'); return cart ? JSON.parse(cart) : []; }
    function saveCart(cart) { localStorage.setItem('tokoMinimalisCart', JSON.stringify(cart)); }
    function addToCart(productId) { let cart = getCart(); const existingProduct = cart.find(item => item.productId === productId); if (existingProduct) { existingProduct.quantity++; } else { cart.push({ productId: productId, quantity: 1 }); } saveCart(cart); updateCartIcon(); showCustomNotification('Ditambahkan!'); }
    function removeFromCart(productId) { let cart = getCart(); cart = cart.filter(item => item.productId !== productId); saveCart(cart); updateCartIcon(); renderCartItems(); }
    function updateCartIcon() { const cart = getCart(); const totalItems = cart.reduce((total, item) => total + item.quantity, 0); const cartBadge = document.getElementById('cart-item-count'); if (cartBadge) { cartBadge.textContent = totalItems; if (totalItems > 0) { cartBadge.classList.remove('hidden'); } else { cartBadge.classList.add('hidden'); } } }
    function renderCartItems() { const cartItemsContainer = document.getElementById('cart-items-container'); if (!cartItemsContainer) return; const cart = getCart(); cartItemsContainer.innerHTML = ''; if (cart.length === 0) { cartItemsContainer.innerHTML = '<p class="empty-cart-msg">Keranjang Anda masih kosong.</p>'; return; } cart.forEach(item => { const product = productsDB.find(p => p.id === item.productId); if (product) { const itemElement = document.createElement('div'); itemElement.className = 'cart-item'; itemElement.innerHTML = `<div class="cart-item-image"><img src="${product.gambar}" alt="${product.nama}"></div><div class="cart-item-info"><h4>${product.nama}</h4><p class="price">Rp${product.harga.toLocaleString('id-ID')} x ${item.quantity}</p></div><button class="remove-item-btn" data-product-id="${product.id}" title="Hapus item"><i class="fas fa-trash-alt"></i></button>`; cartItemsContainer.appendChild(itemElement); } }); }
    function getQueryParam(param) { const urlParams = new URLSearchParams(window.location.search); return urlParams.get(param) ? decodeURIComponent(urlParams.get(param)) : null; }
    function createFeaturedCard(product) { return `<a href="detail-produk.html?id=${product.id}" class="product-card"><img src="${product.gambar}" alt="${product.nama}"><div class="card-label">${product.kategori.toUpperCase()}</div></a>`; }
    function createGridCard(product) { const formattedPrice = `Rp${product.harga.toLocaleString('id-ID')}`; return `<a href="detail-produk.html?id=${product.id}" class="grid-product-card"><img src="${product.gambar}" alt="${product.nama}"><div class="grid-card-info"><h3>${product.nama}</h3><p class="price">${formattedPrice}</p></div></a>`; }
    function displaySearchResults(results) { const resultsContainer = document.getElementById('search-results-dropdown'); if (!resultsContainer) return; resultsContainer.innerHTML = ''; if (results.length === 0 && document.querySelector('#header-search-bar input').value.length > 1) { resultsContainer.innerHTML = '<p style="text-align: center; padding: 20px; color: var(--color-text-secondary);">Produk tidak ditemukan.</p>'; return; } results.forEach(product => { const resultElement = document.createElement('a'); resultElement.href = `detail-produk.html?id=${product.id}`; resultElement.className = 'search-result-item'; resultElement.innerHTML = `<img src="${product.gambar}" alt="${product.nama}"><span>${product.nama}</span>`; resultsContainer.appendChild(resultElement); }); }
    function handleSearchInput(e) { const query = e.target.value.toLowerCase(); const resultsContainer = document.getElementById('search-results-dropdown'); if (!resultsContainer) return; if (query.length > 1) { const filteredProducts = productsDB.filter(product => product.nama.toLowerCase().includes(query)); displaySearchResults(filteredProducts); resultsContainer.classList.add('active'); } else { resultsContainer.classList.remove('active'); } }
    function renderHomePage() { const limitProdukMusiman = 4; const featuredContainer = document.querySelector('.product-carousel'); if (featuredContainer) { const featuredProducts = productsDB.filter(p => p.isUnggulan === true); featuredContainer.innerHTML = featuredProducts.map(createFeaturedCard).join(''); initializeFeaturedCarousel(); } const seasonalGrid = document.querySelector('.seasonal-section .product-grid'); const seasonalTitle = document.querySelector('.seasonal-section h2'); const seeMoreButton = document.querySelector('.seasonal-section .see-more-btn'); if (seasonalGrid && seasonalTitle && seeMoreButton) { const slogan = seasonalSlogans[musimAktif]; seasonalTitle.textContent = slogan ? slogan : "Produk Pilihan Musiman"; const seasonalProducts = productsDB.filter(product => product.tagMusiman === musimAktif).slice(0, limitProdukMusiman); seasonalGrid.innerHTML = seasonalProducts.map(createGridCard).join(''); seeMoreButton.href = `produk-musiman.html?musim=${musimAktif}`; } }
    function renderSeasonalPage() { const seasonFromURL = getQueryParam('musim'); const titleElement = document.getElementById('seasonal-page-title'); const gridElement = document.getElementById('seasonal-products-grid'); if (!seasonFromURL || !titleElement || !gridElement) return; const slogan = seasonalSlogans[seasonFromURL] || "Produk Pilihan"; titleElement.textContent = slogan; const allSeasonalProducts = productsDB.filter(p => p.tagMusiman === seasonFromURL); if (allSeasonalProducts.length > 0) { gridElement.innerHTML = allSeasonalProducts.map(createGridCard).join(''); } else { gridElement.innerHTML = `<p>Produk untuk musim ini tidak ditemukan.</p>`; } }
    function renderAllProductsPage() { const gridElement = document.getElementById('all-products-grid'); if (!gridElement) return; const allProducts = productsDB; if (allProducts.length > 0) { gridElement.innerHTML = allProducts.map(createGridCard).join(''); } else { gridElement.innerHTML = "<p>Belum ada produk untuk ditampilkan.</p>"; } }
    function renderCategoryPage() { const categoryName = getQueryParam('nama'); const titleElement = document.getElementById('kategori-page-title'); const gridElement = document.getElementById('kategori-products-grid'); if (!categoryName || !titleElement || !gridElement) return; const pageTitle = `Kategori: ${categoryName}`; titleElement.textContent = pageTitle; document.title = pageTitle; const productsInCategory = productsDB.filter(p => p.kategori === categoryName); if (productsInCategory.length > 0) { gridElement.innerHTML = productsInCategory.map(createGridCard).join(''); } else { gridElement.innerHTML = `<p>Tidak ada produk dalam kategori "${categoryName}".</p>`; } }
    function renderDetailPage() { const productId = getQueryParam('id'); const container = document.getElementById('product-detail-container'); if (!productId) { container.innerHTML = "<h1>404: ID Produk tidak ditemukan di URL.</h1>"; return; } const product = productsDB.find(p => p.id === productId); if (!product) { container.innerHTML = `<h1>404: Produk dengan ID "${productId}" tidak ditemukan.</h1>`; return; } document.title = product.nama; document.getElementById('product-image').src = product.gambar; document.getElementById('product-image').alt = product.nama; document.getElementById('product-name').textContent = product.nama; document.getElementById('product-price').textContent = `Rp${product.harga.toLocaleString('id-ID')}`; document.getElementById('product-description').textContent = product.deskripsi; const addToCartButton = document.querySelector('.btn-keranjang'); if (addToCartButton) { addToCartButton.addEventListener('click', () => { addToCart(product.id); }); } }
    function initializeFeaturedCarousel() { const carousel = document.querySelector('.product-carousel'); if (!carousel) return; const cards = carousel.querySelectorAll('.product-card'); if (cards.length === 0) return; let currentIndex = 0; const numCards = cards.length; function updateCarousel() { cards.forEach((card, index) => { let offset = index - currentIndex; if (Math.abs(offset) > numCards / 2) { offset > 0 ? offset -= numCards : offset += numCards; } let transform = ""; let opacity = "0"; let zIndex = 0; let direction = offset > 0 ? 1 : -1; if (offset === 0) { transform = "translateX(-50%) scale(1)"; opacity = "1"; zIndex = 10; } else if (offset === 1 || offset === -1) { transform = `translateX(${-50 + 60 * direction}%) scale(0.7) translateZ(-150px)`; opacity = "0.6"; zIndex = 9; } else { transform = `translateX(${-50 + 80 * direction}%) scale(0.5) translateZ(-300px)`; opacity = "0"; zIndex = 8; } card.style.transform = transform; card.style.opacity = opacity; card.style.zIndex = zIndex; }); } let isDragging = false, startX, dragThreshold = 50; function startDrag(e) { isDragging = true; startX = e.pageX || e.touches[0].pageX; } function endDrag(e) { if (!isDragging) return; isDragging = false; const endX = e.pageX || e.changedTouches[0].pageX; const diff = endX - startX; if (Math.abs(diff) > dragThreshold) { diff < 0 ? currentIndex = (currentIndex + 1) % numCards : currentIndex = (currentIndex - 1 + numCards) % numCards; updateCarousel(); } } updateCarousel(); carousel.addEventListener("mousedown", startDrag); carousel.addEventListener("mouseup", endDrag); carousel.addEventListener("mouseleave", endDrag); carousel.addEventListener("touchstart", startDrag); carousel.addEventListener("touchend", endDrag); }
    function setupPanel(buttonId, overlayId, panelId) { const button = document.getElementById(buttonId); const overlay = document.getElementById(overlayId); const panel = document.getElementById(panelId); function closeAllSidePanels() { document.querySelectorAll('.panel-container, .overlay-background').forEach(el => { if (el.id !== 'cart-panel' && el.id !== 'panel-overlay') { el.classList.remove('active'); } }); } if (button && overlay && panel) { const closeBtn = panel.querySelector('.close-btn'); const openPanel = (event) => { event.preventDefault(); closeAllSidePanels(); overlay.classList.add('active'); panel.classList.add('active'); }; const closePanel = () => { overlay.classList.remove('active'); panel.classList.remove('active'); }; button.addEventListener('click', openPanel); if (closeBtn) closeBtn.addEventListener('click', closePanel); overlay.addEventListener('click', closePanel); } }
    
    // --- Inisialisasi Event Listener Panel Keranjang ---
    const cartPanel = document.getElementById('cart-panel'); const panelOverlay = document.getElementById('panel-overlay'); const closeCartBtn = document.getElementById('close-cart-btn'); const cartIcon = document.querySelector('.header-cart-icon'); const cartItemsContainer = document.getElementById('cart-items-container'); const checkoutBtn = document.getElementById('checkout-btn');
    function openCartPanel(e) { e.preventDefault(); renderCartItems(); cartPanel.classList.add('active'); panelOverlay.classList.add('active'); }
    function closeCartPanel() { cartPanel.classList.remove('active'); panelOverlay.classList.remove('active'); }
    if (cartIcon) cartIcon.addEventListener('click', openCartPanel);
    if (closeCartBtn) closeCartBtn.addEventListener('click', closeCartPanel);
    if (panelOverlay) panelOverlay.addEventListener('click', closeCartPanel);
    if (cartItemsContainer) { cartItemsContainer.addEventListener('click', function (e) { if (e.target.closest('.remove-item-btn')) { const productId = e.target.closest('.remove-item-btn').dataset.productId; removeFromCart(productId); } }); }
    if (checkoutBtn) { checkoutBtn.addEventListener('click', () => { const cart = getCart(); if (cart.length === 0) { alert('Keranjang Anda kosong!'); return; } let pesan = "Halo, saya ingin memesan semua barang ini:\n\n"; let totalBelanja = 0; cart.forEach(item => { const product = productsDB.find(p => p.id === item.productId); if (product) { pesan += `${item.quantity}x ${product.nama}\n`; totalBelanja += product.harga * item.quantity; } }); pesan += `\nTotal: Rp${totalBelanja.toLocaleString('id-ID')}`; const nomorWhatsapp = "6281234567890"; const linkWa = `https://wa.me/${nomorWhatsapp}?text=${encodeURIComponent(pesan)}`; window.open(linkWa, '_blank'); closeCartPanel(); }); }
    
    // --- Inisialisasi Pencarian ---
    const headerSearchInput = document.querySelector('#header-search-bar input');
    const searchResultsDropdown = document.getElementById('search-results-dropdown');
    if (headerSearchInput && searchResultsDropdown) {
        headerSearchInput.addEventListener('input', handleSearchInput);
        headerSearchInput.addEventListener('blur', () => { setTimeout(() => { searchResultsDropdown.classList.remove('active'); }, 200); });
        headerSearchInput.addEventListener('focus', handleSearchInput);
    }
    
    // --- Inisialisasi Slider Info ---
    const infoSliderWrapper = document.querySelector('.info-slider .slider-wrapper');
    if (infoSliderWrapper) { let infoSlides = document.querySelectorAll('.info-slider .slide'); if (infoSlides.length > 0) { let infoCurrentIndex = 1; const totalRealSlides = infoSlides.length; let slideInterval; const firstClone = infoSlides[0].cloneNode(!0), lastClone = infoSlides[totalRealSlides - 1].cloneNode(!0); infoSliderWrapper.appendChild(firstClone); infoSliderWrapper.prepend(lastClone); infoSlides = document.querySelectorAll(".info-slider .slide"); function silentTranslate() { infoSliderWrapper.style.transition = "none"; infoSliderWrapper.style.transform = `translateX(-${100 * infoCurrentIndex}%)`; requestAnimationFrame(() => { requestAnimationFrame(() => { infoSliderWrapper.style.transition = "transform 0.5s ease-in-out" }) }) } silentTranslate(); function startInterval() { slideInterval = setInterval(() => { infoCurrentIndex++; infoSliderWrapper.style.transform = `translateX(-${100 * infoCurrentIndex}%)` }, 8000) } infoSliderWrapper.addEventListener("transitionend", () => { if (infoCurrentIndex >= totalRealSlides + 1) { infoCurrentIndex = 1; silentTranslate(); } else if (infoCurrentIndex <= 0) { infoCurrentIndex = totalRealSlides; silentTranslate(); } }); startInterval(); } }

    const route = () => { if (document.querySelector('.product-carousel')) { renderHomePage(); } else if (document.getElementById('seasonal-products-grid')) { renderSeasonalPage(); } else if (document.getElementById('all-products-grid')) { renderAllProductsPage(); } else if (document.getElementById('product-detail-container')) { renderDetailPage(); } else if (document.getElementById('kategori-products-grid')) { renderCategoryPage(); } };
    route();
    updateCartIcon();
    setupPanel('kategori-btn', 'categoryOverlay', 'categoryPanel');
    setupPanel('info-btn', 'infoOverlay', 'infoPanel');
}